// <auto-generated />
using System;
using DoAnQuanLyTienGui.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoAnQuanLyTienGui.Migrations
{
    [DbContext(typeof(QLTGDbcontext))]
    partial class QLTGDbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoAnQuanLyTienGui.Data.GiaoDich", b =>
                {
                    b.Property<string>("MaGiaoDich")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KhachHangMaKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("LoaiGiaoDichMaGiaoDich")
                        .HasColumnType("int");

                    b.Property<string>("MaKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayGiaoDich")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanVienMaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaGiaoDich");

                    b.HasIndex("KhachHangMaKH");

                    b.HasIndex("LoaiGiaoDichMaGiaoDich");

                    b.HasIndex("NhanVienMaNV");

                    b.ToTable("GiaoDich");
                });

            modelBuilder.Entity("DoAnQuanLyTienGui.Data.KhachHang", b =>
                {
                    b.Property<string>("MaKH")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKH");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("DoAnQuanLyTienGui.Data.LoaiGiaoDich", b =>
                {
                    b.Property<int>("MaGiaoDich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGiaoDich"));

                    b.Property<string>("LoaiGD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaGiaoDich");

                    b.ToTable("LoaiGiaoDich");
                });

            modelBuilder.Entity("DoAnQuanLyTienGui.Data.NhanVien", b =>
                {
                    b.Property<string>("MaNV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNV");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("DoAnQuanLyTienGui.Data.SoTietKiem", b =>
                {
                    b.Property<string>("MaSo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KhachHangMaKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("KyHan")
                        .HasColumnType("int");

                    b.Property<string>("MaKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayGui")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanVienMaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("SoTienGui")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaSo");

                    b.HasIndex("KhachHangMaKH");

                    b.HasIndex("NhanVienMaNV");

                    b.ToTable("SoTietKiem");
                });

            modelBuilder.Entity("DoAnQuanLyTienGui.Data.ThongKeChiTiet", b =>
                {
                    b.Property<string>("GiaoDichMaGiaoDich")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KhachHangMaKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("KyHan")
                        .HasColumnType("int");

                    b.Property<string>("LoaiGD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoaiGiaoDichMaGiaoDich")
                        .HasColumnType("int");

                    b.Property<string>("MaGiaoDich")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayGiaoDich")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayGui")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanVienMaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SoTienGui")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SoTietKiemMaSo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("GiaoDichMaGiaoDich");

                    b.HasIndex("KhachHangMaKH");

                    b.HasIndex("LoaiGiaoDichMaGiaoDich");

                    b.HasIndex("NhanVienMaNV");

                    b.HasIndex("SoTietKiemMaSo");

                    b.ToTable("ThongKeChiTiet");
                });

            modelBuilder.Entity("DoAnQuanLyTienGui.Data.GiaoDich", b =>
                {
                    b.HasOne("DoAnQuanLyTienGui.Data.KhachHang", "KhachHang")
                        .WithMany("GiaoDich")
                        .HasForeignKey("KhachHangMaKH")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DoAnQuanLyTienGui.Data.LoaiGiaoDich", "LoaiGiaoDich")
                        .WithMany("GiaoDich")
                        .HasForeignKey("LoaiGiaoDichMaGiaoDich")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DoAnQuanLyTienGui.Data.NhanVien", "NhanVien")
                        .WithMany("GiaoDich")
                        .HasForeignKey("NhanVienMaNV")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("LoaiGiaoDich");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("DoAnQuanLyTienGui.Data.SoTietKiem", b =>
                {
                    b.HasOne("DoAnQuanLyTienGui.Data.KhachHang", "KhachHang")
                        .WithMany("SoTietKiem")
                        .HasForeignKey("KhachHangMaKH")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DoAnQuanLyTienGui.Data.NhanVien", "NhanVien")
                        .WithMany("SoTietKiem")
                        .HasForeignKey("NhanVienMaNV")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("DoAnQuanLyTienGui.Data.ThongKeChiTiet", b =>
                {
                    b.HasOne("DoAnQuanLyTienGui.Data.GiaoDich", "GiaoDich")
                        .WithMany()
                        .HasForeignKey("GiaoDichMaGiaoDich")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DoAnQuanLyTienGui.Data.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangMaKH")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DoAnQuanLyTienGui.Data.LoaiGiaoDich", "LoaiGiaoDich")
                        .WithMany()
                        .HasForeignKey("LoaiGiaoDichMaGiaoDich")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DoAnQuanLyTienGui.Data.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienMaNV")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DoAnQuanLyTienGui.Data.SoTietKiem", "SoTietKiem")
                        .WithMany()
                        .HasForeignKey("SoTietKiemMaSo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("GiaoDich");

                    b.Navigation("KhachHang");

                    b.Navigation("LoaiGiaoDich");

                    b.Navigation("NhanVien");

                    b.Navigation("SoTietKiem");
                });

            modelBuilder.Entity("DoAnQuanLyTienGui.Data.KhachHang", b =>
                {
                    b.Navigation("GiaoDich");

                    b.Navigation("SoTietKiem");
                });

            modelBuilder.Entity("DoAnQuanLyTienGui.Data.LoaiGiaoDich", b =>
                {
                    b.Navigation("GiaoDich");
                });

            modelBuilder.Entity("DoAnQuanLyTienGui.Data.NhanVien", b =>
                {
                    b.Navigation("GiaoDich");

                    b.Navigation("SoTietKiem");
                });
#pragma warning restore 612, 618
        }
    }
}
